# Generated by Django 3.1.4 on 2020-12-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
